### ISSUE TITLE
Set up Drone Cloud CI using ndp

### ISSUE THREAD

**Issue by vielmetti** [mdlayher/ndp#14]
PR to follow.

Set up Drone Cloud CI, with one or more of the following, as first implemented in [Travis CI .travis.yml](https://github.com/mdlayher/ndp/blob/master/.travis.yml).

- [ ] Set up Drone Cloud for a repo in the branch
- [ ] Build ndp
- [ ] Test ndp using static tests (golint, staticcheck)
- [ ] Test ndp using "go test"
- [ ] Test ipv6 status

**Comment by mdlayher** [comment]
I ended up setting up builds.sr.ht, but thanks anyway!

**Comment by vielmetti** [comment]
Nice! thanks
