### ISSUE TITLE
s/Dial/Listen/g? 

### ISSUE THREAD

**Issue by 10000TB** [mdlayher/ndp#21]
func Dial(ifi *net.Interface, addr Addr) (*Conn, net.IP, error) {...}

**Comment by mdlayher** [comment]
Probably could change that yeah. But at this point I'm not sure it's necessary.

**Comment by 10000TB** [comment]
totally not an urgent thing at all     

during an internal discussion, it was    
suggested that language like "Dial"     
is more for client side convention wise      

also within `Dial(ifi *net.Interface, addr Addr)`
there is not a deeper call to any Dialing    
function

**Comment by mdlayher** [comment]
I finally decided to make this change, thanks!
