### ISSUE TITLE
Add SetDeadline/SetWriteDeadline methods?

### ISSUE THREAD

**Issue by nwidger** [mdlayher/ndp#22]
Is there any reason `*Conn` has a `SetReadDeadline` method but not `SetDeadline`/`SetWriteDeadline` methods?  The underlying `*ipv6.PacketConn` provides all three so this seems like it would easy, but I wasn't sure if there was a reason to omit them.

I'd be happy to open a PR creating `SetDeadline` and `SetWriteDeadline` methods if you agree that they should be added.

**Comment by mdlayher** [comment]
Hi there, I'm sorry I missed this. There's no reason for those methods to not be added, but I haven't personally had a need in my own work. PRs absolutely welcome.

**Comment by nwidger** [comment]
No problem!  I just opened #25.
