### ISSUE TITLE
Update README with more informative text

### ISSUE THREAD

**Issue by vielmetti** [mdlayher/ndp#8]
Add to the README with one or more of

* illustrative examples, as in #7 
* build instructions
* usage guidelines
* motivation (why you wrote this, why we should run this)

**Comment by mdlayher** [comment]
Sounds like a great idea!

**Comment by mdlayher** [comment]
Just added a bit more, but as for the motivation section, I will probably do that in a full length blog and then quote it in the README here.

**Comment by mdlayher** [comment]
I think the README is decent at this point, so closing!
